# Generated by Django 4.2.2 on 2023-10-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_rename_customer_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Order',
            new_name='order',
        ),
    ]
